sonarqube:
  elasticsearch:
    configureNode: true
  
  persistence:
    enabled: true
    size: 5Gi
  
  postgresql:
    # --- AQUI ESTA NUESTRO PARCHE GITOPS ---
    image:
      tag: "15" 
    # ---------------------------------------
    persistence:
      enabled: true
      size: 5Gi
